# Generated by Django 2.1.1 on 2018-09-16 05:13

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('start', 'Start Record'), ('end', 'End Record')], default='start', max_length=28, verbose_name='Type')),
                ('record_timestamp', models.DateTimeField(verbose_name='Record Timestamp')),
                ('source', models.CharField(blank=True, max_length=9, null=True)),
                ('destination', models.CharField(blank=True, max_length=9, null=True)),
                ('call_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Call Record',
                'verbose_name_plural': 'Call Records',
            },
        ),
        migrations.CreateModel(
            name='TelephoneBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField(null=True, verbose_name='Call Duration')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Call Price')),
                ('call_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='call_record.CallRecord')),
            ],
            options={
                'verbose_name': 'Telephone Bill',
                'verbose_name_plural': 'Telephone Bills',
            },
        ),
    ]
