# Generated by Django 2.1.1 on 2018-09-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_record', '0002_auto_20180916_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='call_id',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
