# Generated by Django 2.1.1 on 2018-09-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_record', '0003_auto_20180916_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='destination',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='source',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
