# Generated by Django 2.1.1 on 2018-09-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_record', '0004_auto_20180916_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telephonebill',
            name='call_record',
        ),
        migrations.AddField(
            model_name='telephonebill',
            name='destination',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telephonebill',
            name='start_date',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telephonebill',
            name='start_time',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telephonebill',
            name='duration',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
