# Generated by Django 2.1.1 on 2018-09-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_record', '0005_auto_20180917_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='telephonebill',
            name='source',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
