# Generated by Django 2.1.1 on 2018-09-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_record', '0006_telephonebill_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telephonebill',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='telephonebill',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
