# Generated by Django 2.1.1 on 2018-09-04 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('start', 'Call Start Record'), ('end', 'Call Start Record')], default='start', max_length=28, verbose_name='Type')),
                ('record_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Record Timestamp')),
            ],
            options={
                'verbose_name': 'Call Record',
                'verbose_name_plural': 'Call Records',
            },
        ),
        migrations.CreateModel(
            name='EndRecord',
            fields=[
                ('callrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='call_record.CallRecord')),
            ],
            options={
                'verbose_name': 'Call End Record',
                'verbose_name_plural': 'Call End Records',
            },
            bases=('call_record.callrecord',),
        ),
        migrations.CreateModel(
            name='StartRecord',
            fields=[
                ('callrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='call_record.CallRecord')),
                ('source', models.CharField(blank=True, max_length=9, null=True)),
                ('destination', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'verbose_name': 'Call Start Record',
                'verbose_name_plural': 'Call Start Records',
            },
            bases=('call_record.callrecord',),
        ),
        migrations.AddField(
            model_name='endrecord',
            name='start_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='call_record.StartRecord'),
        ),
    ]
