# Generated by Django 2.1.1 on 2018-09-11 00:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephoneBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField(null=True, verbose_name='Call Duration')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Call Price')),
                ('start_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='call_record.StartRecord')),
            ],
            options={
                'verbose_name_plural': 'Telephone Bills',
                'verbose_name': 'Telephone Bill',
            },
        ),
        migrations.AlterField(
            model_name='endrecord',
            name='start_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end_record', to='call_record.StartRecord'),
        ),
    ]
