# Generated by Django 2.1.1 on 2018-09-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_record', '0002_auto_20180911_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='record_timestamp',
            field=models.DateTimeField(verbose_name='Record Timestamp'),
        ),
    ]
